### ISSUE TITLE
How to add a pattern ?

### ISSUE THREAD

**Issue by trebmuh** [jthwho/SickBeatBetty#4]
Looking at [this screenshot](https://thebeatcommunity.com/2023/01/30/have-you-downloaded-sick-beat-betty-a-free-download/), it seems that I should be able to add more "patterns" than the default one.

So far, I'm unable to do so. 
Could you please tell me how is it supposed to work?

![sickbeatbetty](https://user-images.githubusercontent.com/8705846/218303673-9902e62b-5082-4ad0-8dba-6bbd0c0ac34e.png)

Note: running it on GNU/linux, built from 720b59b

**Comment by trebmuh** [comment]
Got it, a right-click + duplicate.
Closing now.

**Comment by jthwho** [comment]
Sorry about that, didn't see this until now.  Need to figure out GitHub notification.  Anyways, yea, you got it.  Probably should add a button to make it obvious, sorry about that.

**Comment by trebmuh** [comment]
That's all good @jthwho .
Thanks for this software.
