### ISSUE TITLE
VST3 not recognised in FL Studio

### ISSUE THREAD

**Issue by ajh101** [jthwho/SickBeatBetty#5]
I have tried 1.03 (32 bit and 64 bit) as well as 1.04 (64 bit), but even after scanning to refresh all plugins, I cannot see Sick Beat Betty :(

**Comment by jthwho** [comment]
Did you add the Sick Beat Betty install path to your plugin search paths?  The default install path is C:\Program Files\Sick Beat Betty.  I've been meaning to adjust the installer to put it in the "standard" VST path, but haven't yet gotten to it yet.

Here's how I've got it setup in Bitwig:
![image](https://user-images.githubusercontent.com/18428817/219145460-041150a1-b18e-4c97-a460-bc9cdf165d11.png)

**Comment by ajh101** [comment]
Apologies I should have mentioned - yes I added both the 32 and 64 bit paths. 

Edit: I manually moved the VST3 file, to the Common Files/VST3 folder and all is well! :)
